linters:
  enable-all: true

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 12
  maligned:
    suggest-new: true
  misspell:
    locale: US
  lll:
    line-length: 80
    tab-width: 4
  goimports:
    local-prefixes: github.com/KibaFox/tls-usr-sessions

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gochecknoglobals

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.16.x # use the fixed version
